"""talents model and remove wrong fields from user

Revision ID: 056eda9b0aa6
Revises: 6bb05c4620b2
Create Date: 2026-01-23 16:55:33.997488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056eda9b0aa6'
down_revision = '6bb05c4620b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('last_row', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('talents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('shoe_size', sa.String(length=10), nullable=True),
    sa.Column('clothing_size', sa.String(length=20), nullable=True),
    sa.Column('has_visa', sa.Boolean(), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('pix_key', sa.String(length=120), nullable=True),
    sa.Column('photo_face_path', sa.String(length=300), nullable=True),
    sa.Column('photo_full_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talents')
    op.drop_table('import_state')
    # ### end Alembic commands ###
