"""email_notifications

Revision ID: 1f8f3e83f839
Revises: d2a5281970c7
Create Date: 2026-03-13 21:18:47.870769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8f3e83f839'
down_revision = 'd2a5281970c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_changed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_talents_password_reset_token', ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_talents_password_reset_token', type_='unique')
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_column('event_changed_at')

    # ### end Alembic commands ###
