"""add clothing size top and bottom

Revision ID: 22bcb37ab1bd
Revises: 595b18b12e5f
Create Date: 2026-01-27 14:50:06.594752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bcb37ab1bd'
down_revision = '595b18b12e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clothing_size_top', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('clothing_size_bottom', sa.String(length=20), nullable=True))
        batch_op.drop_column('clothing_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clothing_size', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('clothing_size_bottom')
        batch_op.drop_column('clothing_size_top')

    # ### end Alembic commands ###
