"""event_role_type

Revision ID: 33a18b69f722
Revises: afe6a233508f
Create Date: 2026-03-13 17:49:11.203256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a18b69f722'
down_revision = 'afe6a233508f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_type', sa.String(length=20), server_default='character', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_column('role_type')

    # ### end Alembic commands ###
