"""commission_payment_receives_commission_sale_date

Revision ID: 3f922f167be5
Revises: 49ded2445b6b
Create Date: 2026-05-25 22:42:31.988512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f922f167be5'
down_revision = '49ded2445b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(length=200), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='a_pagar', nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['commission_payments.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_payments', schema=None) as batch_op:
        batch_op.create_index('ix_commission_payments_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_commission_payments_seller_id', ['seller_id'], unique=False)
        batch_op.create_index('ix_commission_payments_status', ['status'], unique=False)

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receives_commission', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('receives_commission')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('sale_date')

    with op.batch_alter_table('commission_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_commission_payments_status')
        batch_op.drop_index('ix_commission_payments_seller_id')
        batch_op.drop_index('ix_commission_payments_event_id')

    op.drop_table('commission_payments')
    # ### end Alembic commands ###
