"""salary_payment_user_pix

Revision ID: 4511fd62d394
Revises: a79cd613a26d
Create Date: 2026-05-26 21:58:54.884528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4511fd62d394'
down_revision = 'a79cd613a26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_history_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default='nao_pago', nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('month_ref', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salary_history_id'], ['salary_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'due_date', name='uq_salary_payment_user_due')
    )
    with op.batch_alter_table('salary_payments', schema=None) as batch_op:
        batch_op.create_index('ix_salary_payments_month_ref', ['month_ref'], unique=False)
        batch_op.create_index('ix_salary_payments_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pix_key_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pix_key_type')
        batch_op.drop_column('pix_key')

    with op.batch_alter_table('salary_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_salary_payments_user_id')
        batch_op.drop_index('ix_salary_payments_month_ref')

    op.drop_table('salary_payments')
    # ### end Alembic commands ###
