"""event_ratings_and_sub_ratings

Revision ID: 4af0ad1b286b
Revises: 4868e4040dfe
Create Date: 2026-05-14 22:47:46.521116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af0ad1b286b'
down_revision = '4868e4040dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('detail_submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'talent_id', name='uq_event_rating')
    )
    with op.batch_alter_table('event_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_event_ratings_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_ratings_talent_id', ['talent_id'], unique=False)

    op.create_table('event_sub_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subject_talent_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['event_ratings.id'], ),
    sa.ForeignKeyConstraint(['subject_talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_sub_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_event_sub_ratings_rating_id', ['rating_id'], unique=False)
        batch_op.create_index('ix_event_sub_ratings_subject', ['subject_talent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_sub_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_event_sub_ratings_subject')
        batch_op.drop_index('ix_event_sub_ratings_rating_id')

    op.drop_table('event_sub_ratings')
    with op.batch_alter_table('event_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_event_ratings_talent_id')
        batch_op.drop_index('ix_event_ratings_event_id')

    op.drop_table('event_ratings')
    # ### end Alembic commands ###
