"""expand talent fields

Revision ID: 595b18b12e5f
Revises: 056eda9b0aa6
Create Date: 2026-01-23 18:52:49.173757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595b18b12e5f'
down_revision = '056eda9b0aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artistic_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email_contact', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('passport_visa_text', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pix_key_secondary', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cnh_file_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cnh_expiration', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('car_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('car_brand', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('car_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('car_plate', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.drop_column('car_plate')
        batch_op.drop_column('car_year')
        batch_op.drop_column('car_brand')
        batch_op.drop_column('car_model')
        batch_op.drop_column('cnh_expiration')
        batch_op.drop_column('cnh_file_path')
        batch_op.drop_column('pix_key_secondary')
        batch_op.drop_column('passport_visa_text')
        batch_op.drop_column('race')
        batch_op.drop_column('languages')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('email_contact')
        batch_op.drop_column('phone')
        batch_op.drop_column('artistic_name')

    # ### end Alembic commands ###
