"""event_type_parent_event_id

Revision ID: 5f0bc36d5f3a
Revises: bd402570ff69
Create Date: 2026-03-03 19:16:17.490085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0bc36d5f3a'
down_revision = 'bd402570ff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('parent_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_events_parent', 'calendar_events', ['parent_event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_parent', type_='foreignkey')
        batch_op.drop_column('parent_event_id')
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
