"""crm_tables

Revision ID: 6ef8bc59b9bc
Revises: d290110922b3
Create Date: 2026-03-16 17:58:16.788476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef8bc59b9bc'
down_revision = 'd290110922b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['crm_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('lost_reason', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('contractor_cpf', sa.String(length=20), nullable=True),
    sa.Column('contractor_email', sa.String(length=120), nullable=True),
    sa.Column('contractor_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('contractor_address', sa.String(length=300), nullable=True),
    sa.Column('birthday_person', sa.String(length=200), nullable=True),
    sa.Column('birthday_age', sa.String(length=10), nullable=True),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('character_count', sa.String(length=20), nullable=True),
    sa.Column('characters', sa.Text(), nullable=True),
    sa.Column('event_theme', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('service_period', sa.String(length=100), nullable=True),
    sa.Column('venue_type', sa.String(length=60), nullable=True),
    sa.Column('venue_cep', sa.String(length=10), nullable=True),
    sa.Column('venue_street', sa.String(length=200), nullable=True),
    sa.Column('venue_number', sa.String(length=20), nullable=True),
    sa.Column('venue_complement', sa.String(length=100), nullable=True),
    sa.Column('venue_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('venue_city', sa.String(length=100), nullable=True),
    sa.Column('venue_state', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=60), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('contractual_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['crm_organizations.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['crm_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_reminders')
    op.drop_table('crm_notes')
    op.drop_table('crm_deals')
    op.drop_table('crm_contacts')
    op.drop_table('crm_stages')
    op.drop_table('crm_organizations')
    # ### end Alembic commands ###
