"""figurino_native_fields

Revision ID: 7cea4da9e282
Revises: b2c3d4e5f6a7
Create Date: 2026-03-02 20:58:16.357721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cea4da9e282'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('figurino_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('pieces', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('figurino_sheets', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('pieces')
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
