"""financial fields and salary history

Revision ID: 99842e33b819
Revises: 790deb9417c0
Create Date: 2026-02-26 11:55:58.599958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99842e33b819'
down_revision = '790deb9417c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('with_invoice', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_events_seller_id', 'users', ['seller_id'], ['id'])

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_commission_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('default_commission_rate')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_seller_id', type_='foreignkey')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('with_invoice')
        batch_op.drop_column('sale_value')

    op.drop_table('salary_history')
    # ### end Alembic commands ###
