"""add_indexes

Revision ID: a9240eaf2fe1
Revises: a9f3b21c0e47
Create Date: 2026-04-06 18:25:40.427566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9240eaf2fe1'
down_revision = 'a9f3b21c0e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_events_seller_id', ['seller_id'], unique=False)
        batch_op.create_index('ix_calendar_events_start_at', ['start_at'], unique=False)

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.create_index('ix_crm_deals_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_crm_deals_stage_id', ['stage_id'], unique=False)

    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.create_index('ix_crm_notes_deal_id', ['deal_id'], unique=False)

    with op.batch_alter_table('crm_reminders', schema=None) as batch_op:
        batch_op.create_index('ix_crm_reminders_deal_id', ['deal_id'], unique=False)

    with op.batch_alter_table('ensaio_materials', schema=None) as batch_op:
        batch_op.create_index('ix_ensaio_materials_event_id', ['event_id'], unique=False)

    with op.batch_alter_table('event_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_event_contracts_event_id', ['event_id'], unique=False)

    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index('ix_event_logs_event_id', ['event_id'], unique=False)

    with op.batch_alter_table('event_payments', schema=None) as batch_op:
        batch_op.create_index('ix_event_payments_event_id', ['event_id'], unique=False)

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.create_index('ix_event_roles_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_event_roles_talent_id', ['talent_id'], unique=False)

    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.create_index('ix_salary_history_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('clicksign_sandbox',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('talent_media', schema=None) as batch_op:
        batch_op.create_index('ix_talent_media_talent_id', ['talent_id'], unique=False)

    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.create_index('ix_talents_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.drop_index('ix_talents_status')

    with op.batch_alter_table('talent_media', schema=None) as batch_op:
        batch_op.drop_index('ix_talent_media_talent_id')

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('clicksign_sandbox',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.drop_index('ix_salary_history_user_id')

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_event_roles_talent_id')
        batch_op.drop_index('ix_event_roles_event_id')

    with op.batch_alter_table('event_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_event_payments_event_id')

    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_event_logs_event_id')

    with op.batch_alter_table('event_contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_event_contracts_event_id')

    with op.batch_alter_table('ensaio_materials', schema=None) as batch_op:
        batch_op.drop_index('ix_ensaio_materials_event_id')

    with op.batch_alter_table('crm_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_reminders_deal_id')

    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_notes_deal_id')

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_deals_stage_id')
        batch_op.drop_index('ix_crm_deals_assigned_to')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_events_start_at')
        batch_op.drop_index('ix_calendar_events_seller_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_created_at')

    # ### end Alembic commands ###
