"""talent_extra_fields

Revision ID: afe6a233508f
Revises: eb9e92165788
Create Date: 2026-03-13 17:31:45.107470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe6a233508f'
down_revision = 'eb9e92165788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('doc_photo_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('pix_key_type', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('worked_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('how_found_us', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.drop_column('how_found_us')
        batch_op.drop_column('worked_before')
        batch_op.drop_column('pix_key_type')
        batch_op.drop_column('doc_photo_path')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
