"""event_role_payment_status

Revision ID: bd402570ff69
Revises: 7cea4da9e282
Create Date: 2026-03-03 16:10:52.066401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd402570ff69'
down_revision = '7cea4da9e282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), server_default='nao_pago', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
