"""logistics_fields

Revision ID: d290110922b3
Revises: 1f8f3e83f839
Create Date: 2026-03-16 11:30:19.209646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd290110922b3'
down_revision = '1f8f3e83f839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('makeup_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('makeup_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('travel_time_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manto_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('departure_margin_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('google_maps_api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('google_maps_api_key')
        batch_op.drop_column('departure_margin_minutes')
        batch_op.drop_column('manto_address')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('travel_time_minutes')
        batch_op.drop_column('departure_time')
        batch_op.drop_column('makeup_location')
        batch_op.drop_column('makeup_time')

    # ### end Alembic commands ###
