"""talent_portal_fields

Revision ID: d2a5281970c7
Revises: 20dd164126ac
Create Date: 2026-03-13 18:07:14.634064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a5281970c7'
down_revision = '20dd164126ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talents', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_column('invite_status')

    # ### end Alembic commands ###
