"""event_source_needs_rehearsal

Revision ID: eb9e92165788
Revises: 5f0bc36d5f3a
Create Date: 2026-03-03 19:51:59.092329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9e92165788'
down_revision = '5f0bc36d5f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_rehearsal', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='google_calendar', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('needs_rehearsal')

    # ### end Alembic commands ###
